# vim: nospell
#
language: minimal
dist: xenial

cache:
  timeout: 600
  directories:
    - $HOME/.stack/snapshots
    - $HOME/.local/bin
    - $TRAVIS_BUILD_DIR/.stack-work

before_cache:
  # - rm -rf $(stack path --local-install-root)/bin
  - rm -rf $(stack path --local-install-root)/doc

addons:
  apt:
    sources: &apt_sources
      - hvr-ghc
      - ubuntu-toolchain-r-test
      - llvm-toolchain-xenial
    packages: &apt_packages
      - dpkg
      - gcc-8
      - g++-8
      - libgmp-dev
      - libgmp-dev
      - happy-1.19.5
      - alex-3.1.7

matrix:
  fast_finish: true
  include:
    - env: GHC=8.6.5 LLVM=8.0.1 CUDA=10.1.105-1
      compiler: "GHC 8.6"
      addons:
        apt:
          sources:
            - *apt_sources
            - llvm-toolchain-xenial-8
          packages:
            - *apt_packages
            - llvm-8-dev

    - env: GHC=8.4.3 LLVM=6.0.1 CUDA=10.0.130-1
      compiler: "GHC 8.4"
      addons:
        apt:
          sources:
            - *apt_sources
            - llvm-toolchain-xenial-6.0
          packages:
            - *apt_packages
            - llvm-6.0-dev

    - env: GHC=8.2.2 LLVM=5.0.2 CUDA=8.0.61-1
      compiler: "GHC 8.2"
      addons:
        apt:
          sources:
            - *apt_sources
            - llvm-toolchain-xenial-5.0
          packages:
            - *apt_packages
            - llvm-5.0-dev

    - env: GHC=8.0.2 LLVM=4.0.1 CUDA=8.0.61-1
      compiler: "GHC 8.0"
      addons:
        apt:
          sources:
            - *apt_sources
            - llvm-toolchain-xenial-4.0
          packages:
            - *apt_packages
            - llvm-4.0-dev

before_install:
  - export PATH=/opt/alex/3.1.7/bin:/opt/happy/1.19.5/bin:$PATH
  - source .travis/install-cuda-xenial.sh
  - source .travis/install-stack.sh

  # llvm-hs requires new g++
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-8 60 --slave /usr/bin/g++ g++ /usr/bin/g++-8

  # ghc-8.4+ require libffi7
  - export LD_LIBRARY_PATH=$(stack exec ghc -- --print-libdir)/rts:$LD_LIBRARY_PATH

  # build environment
  - echo "$(stack exec ghc -- --version) [$(stack exec ghc -- --print-project-git-commit-id 2> /dev/null || echo '?')]"
  - stack --version
  - llc-${LLVM:0:3} --version; true
  - opt-${LLVM:0:3} --version; true

install:
  # how much do we have to do?
  - export FLAGS="--no-terminal --no-copy-bins"
  - stack build $FLAGS --test --dry-run

  # build dependencies
  - travis_retry travis_wait 60 stack build --test --only-dependencies ${FLAGS}

script:
  - travis_retry stack build --test --no-run-tests --haddock --no-haddock-deps ${FLAGS}
  - stack test accelerate-bignum:test-llvm-native || exit 1

after_success:
  - source .travis/update-accelerate-buildbot.sh

